[package]
name = "wave_tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
chrono = "0.4.22"
rodio = "0.15.0"
web-audio-api = "0.22.0"